"""Frozen schema metadata for TPEX common-stock research features."""

from __future__ import annotations

from .price_volume_schema import (
    PRICE_VOLUME_AVAILABILITY_MODES,
    PRICE_VOLUME_FEATURE_FORMULAS,
    PRICE_VOLUME_FEATURE_NAMES,
    PRICE_VOLUME_PRICE_BASIS,
    RESEARCH_SCHEDULING_HINT_REASON,
    price_volume_feature_spec,
)


_SPEC = price_volume_feature_spec("TPEX")
TPEX_PRICE_VOLUME_FEATURE_SCHEMA_VERSION = _SPEC.schema_version
TPEX_PRICE_VOLUME_FEATURE_SCHEMA_HASH = _SPEC.schema_hash
TPEX_PRICE_VOLUME_PRICE_BASIS = PRICE_VOLUME_PRICE_BASIS
TPEX_PRICE_VOLUME_AVAILABILITY_MODES = PRICE_VOLUME_AVAILABILITY_MODES
TPEX_RESEARCH_SCHEDULING_HINT_REASON = RESEARCH_SCHEDULING_HINT_REASON
TPEX_PRICE_VOLUME_FEATURE_FORMULAS = PRICE_VOLUME_FEATURE_FORMULAS
TPEX_PRICE_VOLUME_FEATURE_NAMES = PRICE_VOLUME_FEATURE_NAMES


__all__ = [
    "TPEX_PRICE_VOLUME_AVAILABILITY_MODES",
    "TPEX_PRICE_VOLUME_FEATURE_FORMULAS",
    "TPEX_PRICE_VOLUME_FEATURE_NAMES",
    "TPEX_PRICE_VOLUME_FEATURE_SCHEMA_HASH",
    "TPEX_PRICE_VOLUME_FEATURE_SCHEMA_VERSION",
    "TPEX_PRICE_VOLUME_PRICE_BASIS",
    "TPEX_RESEARCH_SCHEDULING_HINT_REASON",
]
