"""Backward-compatible TWSE names for the shared price/volume schema."""

from __future__ import annotations

from .price_volume_schema import (
    PRICE_VOLUME_AVAILABILITY_MODES,
    PRICE_VOLUME_FEATURE_FORMULAS,
    PRICE_VOLUME_FEATURE_NAMES,
    PRICE_VOLUME_PRICE_BASIS,
    RESEARCH_SCHEDULING_HINT_REASON,
    price_volume_feature_spec,
)


_SPEC = price_volume_feature_spec("TWSE")
TWSE_PRICE_VOLUME_FEATURE_SCHEMA_VERSION = _SPEC.schema_version
TWSE_PRICE_VOLUME_FEATURE_SCHEMA_HASH = _SPEC.schema_hash
TWSE_PRICE_VOLUME_PRICE_BASIS = PRICE_VOLUME_PRICE_BASIS
TWSE_PRICE_VOLUME_AVAILABILITY_MODES = PRICE_VOLUME_AVAILABILITY_MODES
TWSE_RESEARCH_SCHEDULING_HINT_REASON = RESEARCH_SCHEDULING_HINT_REASON
TWSE_PRICE_VOLUME_FEATURE_FORMULAS = PRICE_VOLUME_FEATURE_FORMULAS
TWSE_PRICE_VOLUME_FEATURE_NAMES = PRICE_VOLUME_FEATURE_NAMES


__all__ = [
    "TWSE_PRICE_VOLUME_AVAILABILITY_MODES",
    "TWSE_PRICE_VOLUME_FEATURE_FORMULAS",
    "TWSE_PRICE_VOLUME_FEATURE_NAMES",
    "TWSE_PRICE_VOLUME_FEATURE_SCHEMA_HASH",
    "TWSE_PRICE_VOLUME_FEATURE_SCHEMA_VERSION",
    "TWSE_PRICE_VOLUME_PRICE_BASIS",
    "TWSE_RESEARCH_SCHEDULING_HINT_REASON",
]
